### PR TITLE
Init frontend react, take 2

### PR DESCRIPTION
**Pull request by brandonkeao**

### CODE REVIEW

**Comment by mosesmc52** [comment]
Good job. 

Before I merge the frontend, I want replace the current template with the react template. I'll continue where you left off.

**Comment by brandonkeao** [comment]
The generic D3 map is now in place in React. I only did the US topology data. Its a blank slate awaiting overlayed data from the backend.

**Comment by mosesmc52** [comment]
Good Job. The app just needs one fix before I approve. The responsive WaterBeacon title should remain together and the search menu bar should remain on the page. Instead of search, it should say subscribe. 


Screen Shot 2019-04-22 at 5 26 56 PM

**Comment by brandonkeao** [comment]
I made the updates you requested. Looks like some odd merge conflicts now exist in the Readme...

**Pull request merged**
